'use client';

import Link from 'next/link';
import { useState } from 'react';
import { Badge, Button, Card, EmptyState, Input, Select } from '../ui/primitives';
import { Rating } from '../discovery/MarketplaceCards';
import { formatMoney } from '../../types/money';
import type { BookingStatus } from '../../types/booking';
import type { PaymentStatus } from '../../types/payment';
import { providerBookings, providerProfile, providerReviews, providerSchedule, providerServices, providerTransactions, type ProviderBooking, type ProviderReview } from '../../data/provider-fixtures';

const providerLinks = [
  { href: '/provider', label: 'Dashboard' },
  { href: '/provider/bookings', label: 'Bookings' },
  { href: '/provider/schedule', label: 'Schedule' },
  { href: '/provider/services', label: 'Services' },
  { href: '/provider/earnings', label: 'Earnings' },
  { href: '/provider/reviews', label: 'Reviews' },
  { href: '/provider/profile', label: 'Profile' },
];

const bookingLabels: Record<BookingStatus, string> = { draft: 'Draft', requested: 'Pending request', provider_review: 'Pending request', rejected: 'Declined', accepted: 'Accepted', reschedule_requested: 'Reschedule requested', scheduled: 'Confirmed', in_progress: 'In progress', completion_pending: 'Completion pending', completed: 'Completed', cancelled: 'Cancelled', no_show: 'No-show', refund_pending: 'Refund pending', closed: 'Closed' };
const paymentLabels: Record<PaymentStatus, string> = { pending: 'Pending', initiated: 'Initiated', authorized: 'Authorized', captured: 'Paid', failed: 'Failed', cancelled: 'Cancelled', partially_refunded: 'Partially refunded', refunded: 'Refunded', disputed: 'Disputed', settled: 'Settled', closed: 'Closed' };

export function ProviderStatusBadge({ status }: { status: BookingStatus }) {
  const tone = status === 'completed' || status === 'scheduled' || status === 'accepted' ? 'success' : status === 'cancelled' || status === 'rejected' || status === 'no_show' ? 'danger' : status === 'provider_review' || status === 'requested' || status === 'reschedule_requested' ? 'warning' : 'info';
  return <Badge tone={tone}>{bookingLabels[status]}</Badge>;
}

export function ProviderPaymentBadge({ status }: { status: PaymentStatus }) {
  const tone = status === 'captured' || status === 'settled' || status === 'authorized' ? 'success' : status === 'failed' || status === 'cancelled' ? 'danger' : status === 'pending' || status === 'initiated' ? 'warning' : 'neutral';
  return <Badge tone={tone}>Payment {paymentLabels[status]}</Badge>;
}

export function ProviderShell({ children, active }: { children: React.ReactNode; active: string }) {
  return <div className="provider-layout"><aside className="provider-sidebar"><div className="provider-sidebar-heading"><div className="provider-avatar provider-avatar-large" aria-hidden="true">BS</div><div><strong>{providerProfile.business_name}</strong><span>Provider workspace</span></div></div><nav aria-label="Provider workspace navigation">{providerLinks.map((link) => <Link href={link.href} className={active === link.href ? 'provider-nav-active' : ''} aria-current={active === link.href ? 'page' : undefined} key={link.href}>{link.label}{link.href === '/provider/bookings' ? <span className="provider-nav-count">{providerBookings.filter((booking) => booking.status === 'provider_review').length}</span> : null}</Link>)}</nav><Link href="/" className="provider-exit-link">View marketplace</Link></aside><main className="provider-content">{children}</main></div>;
}

export function ProviderDashboardSummary({ label, value, detail, tone = 'neutral' }: { label: string; value: string; detail: string; tone?: 'neutral' | 'success' | 'warning' | 'info' }) {
  return <Card className="provider-summary-card"><span className="eyebrow">{label}</span><strong>{value}</strong><span className={`provider-summary-detail provider-detail-${tone}`}>{detail}</span></Card>;
}

export function ProviderBookingCard({ booking, onStatusChange }: { booking: ProviderBooking; onStatusChange?: (id: string, status: BookingStatus) => void }) {
  return <Card className="provider-booking-card"><div className="provider-booking-top"><div><span className="eyebrow">{booking.booking_reference}</span><h2>{booking.customer_name}</h2></div><ProviderStatusBadge status={booking.status} /></div><p className="provider-service-name">{booking.provider_name} · {booking.service_id === providerServices[0]?.id ? 'Home electrical inspection' : 'Service appointment'}</p><dl className="provider-booking-details"><div><dt>When</dt><dd>{booking.date_label}, {booking.time}</dd></div><div><dt>Mode</dt><dd>{booking.location}</dd></div><div><dt>Value</dt><dd>{formatMoney(booking.price)}</dd></div></dl><div className="provider-booking-footer"><ProviderPaymentBadge status={booking.payment_status} /><div className="provider-actions"><Link href={`/provider/bookings/${booking.id}`} className="text-link">View details</Link>{onStatusChange && booking.status === 'provider_review' ? <><Button type="button" variant="secondary" onClick={() => onStatusChange(booking.id, 'accepted')}>Accept</Button><Button type="button" variant="quiet" onClick={() => onStatusChange(booking.id, 'rejected')}>Decline</Button></> : null}{onStatusChange && booking.status === 'scheduled' ? <Button type="button" variant="secondary" onClick={() => onStatusChange(booking.id, 'in_progress')}>Start service</Button> : null}{onStatusChange && booking.status === 'in_progress' ? <Button type="button" onClick={() => onStatusChange(booking.id, 'completed')}>Mark complete</Button> : null}</div></div>{booking.customer_note ? <p className="provider-customer-note">Customer note: {booking.customer_note}</p> : null}</Card>;
}

export function ProviderBookingList() {
  const [items, setItems] = useState(providerBookings);
  const [filter, setFilter] = useState('all');
  const updateStatus = (id: string, status: BookingStatus) => setItems((current) => current.map((booking) => booking.id === id ? { ...booking, status } : booking));
  const visible = items.filter((booking) => filter === 'all' || booking.status === filter);
  return <ProviderShell active="/provider/bookings"><ProviderHeading eyebrow="Operations" title="Bookings" description="Review incoming requests and track service work in local presentation state." /><div className="provider-toolbar"><Select label="Filter bookings" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All statuses</option><option value="provider_review">Pending requests</option><option value="scheduled">Confirmed</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></Select><span className="provider-fixture-note">Actions update this screen only.</span></div>{visible.length ? <div className="provider-booking-list">{visible.map((booking) => <ProviderBookingCard booking={booking} onStatusChange={updateStatus} key={booking.id} />)}</div> : <Card><EmptyState title="No bookings in this state">New provider booking activity will appear here.</EmptyState></Card>}</ProviderShell>;
}

export function ProviderHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) {
  return <section className="provider-page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action ? <div className="provider-heading-action">{action}</div> : null}</section>;
}

export function ProviderSchedule() {
  const [selectedDay, setSelectedDay] = useState(providerSchedule[0].day);
  const day = providerSchedule.find((item) => item.day === selectedDay) ?? providerSchedule[0];
  return <ProviderShell active="/provider/schedule"><ProviderHeading eyebrow="Availability" title="Schedule" description="Review working hours, breaks, blocked periods, and booked slots from local presentation data." action={<Button type="button" variant="secondary" onClick={() => undefined}>Add availability</Button>} /><div className="schedule-day-tabs" role="tablist" aria-label="Schedule days">{providerSchedule.map((item) => <button type="button" role="tab" aria-selected={item.day === selectedDay} className={item.day === selectedDay ? 'schedule-day-active' : ''} onClick={() => setSelectedDay(item.day)} key={item.day}><strong>{item.day.slice(0, 3)}</strong><span>{item.date_label.slice(0, 6)}</span></button>)}</div><Card className="schedule-day-panel"><div className="schedule-panel-heading"><div><span className="eyebrow">{day.date_label}</span><h2>{day.day}</h2></div><Badge tone={day.working ? 'success' : 'neutral'}>{day.working ? 'Working day' : 'Day off'}</Badge></div>{day.ranges.length ? <div className="schedule-ranges">{day.ranges.map((range) => <div className={`schedule-range schedule-range-${range.kind}`} key={range.label}><span className="schedule-range-marker" aria-hidden="true" /> <strong>{range.label}</strong><span>{range.kind === 'available' ? 'Available' : range.kind === 'break' ? 'Break' : range.kind === 'booked' ? 'Booked slot' : 'Blocked'}</span></div>)}</div> : <EmptyState title="No availability">This day is currently shown as unavailable.</EmptyState>}</Card><p className="provider-fixture-note">Availability controls are a presentation preview. No calendar or schedule state is changed.</p></ProviderShell>;
}

export function ProviderServiceCard({ service }: { service: typeof providerServices[number] }) {
  const [active, setActive] = useState(true);
  return <Card className="provider-service-card"><div className="provider-service-top"><div><span className="eyebrow">{service.location}</span><h2>{service.service_name.values.en}</h2></div><Badge tone={active ? 'success' : 'neutral'}>{active ? 'Active' : 'Paused'}</Badge></div><p>{service.description.values.en}</p><div className="provider-service-meta"><span>{formatMoney(service.pricing.base_price)}</span><span>{service.duration_minutes} minutes</span><Rating value={service.rating} count={service.review_count} /></div><div className="provider-actions"><Button type="button" variant="quiet" onClick={() => undefined}>View</Button><Button type="button" variant="secondary" onClick={() => undefined}>Edit</Button><Button type="button" variant="quiet" onClick={() => setActive((value) => !value)}>{active ? 'Deactivate' : 'Activate'}</Button></div><p className="provider-fixture-note">Changes are local presentation state.</p></Card>;
}

export function ProviderServices() {
  return <ProviderShell active="/provider/services"><ProviderHeading eyebrow="Catalog" title="Services" description="Manage the services shown on your provider profile using presentation-only controls." action={<Button type="button" onClick={() => undefined}>Add service</Button>} /><div className="provider-service-grid">{providerServices.map((service) => <ProviderServiceCard service={service} key={service.id} />)}</div><p className="provider-fixture-note">Service status, pricing, and ratings are illustrative fixture data.</p></ProviderShell>;
}

export function ProviderEarnings() {
  return <ProviderShell active="/provider/earnings"><ProviderHeading eyebrow="Operations" title="Earnings overview" description="A presentation view of service value and payment status. No payouts or balances are connected." /><div className="provider-summary-grid"><ProviderDashboardSummary label="Available balance" value="INR 8,420.00" detail="Illustrative only" tone="success" /><ProviderDashboardSummary label="Pending earnings" value="INR 2,050.00" detail="3 fixture bookings" tone="warning" /><ProviderDashboardSummary label="This month" value="INR 14,680.00" detail="12 completed jobs" tone="info" /><ProviderDashboardSummary label="Total earnings" value="INR 98,240.00" detail="Presentation history" /></div><Card className="provider-transactions"><div className="section-heading"><div><span className="eyebrow">Recent activity</span><h2>Transactions and payout states</h2></div><Badge tone="warning">No live payouts</Badge></div><div className="provider-transaction-list">{providerTransactions.map((transaction) => <div key={transaction.id}><div><strong>{transaction.label}</strong><span>{transaction.date_label}</span></div><strong>{formatMoney({ amount: transaction.amount, currency: 'INR' })}</strong><ProviderPaymentBadge status={transaction.status} /></div>)}</div><p className="provider-fixture-note">Payment statuses are read-only fixtures and do not represent a wallet or settlement ledger.</p></Card></ProviderShell>;
}

export function ProviderReviews() {
  return <ProviderShell active="/provider/reviews"><ProviderHeading eyebrow="Customer voice" title="Reviews" description="Understand how customers describe completed fixture services." /><div className="provider-review-summary"><ProviderDashboardSummary label="Average rating" value="4.8 / 5" detail="Across 334 reviews" tone="success" /><ProviderDashboardSummary label="Five-star share" value="86%" detail="Rating distribution fixture" tone="info" /></div><Card className="provider-rating-distribution"><h2>Rating distribution</h2>{[['5 stars', '86%'], ['4 stars', '10%'], ['3 stars or below', '4%']].map(([label, value]) => <div key={label}><span>{label}</span><i><b style={{ width: value }} /></i><strong>{value}</strong></div>)}</Card><div className="provider-review-list">{providerReviews.map((review) => <ProviderReviewCard review={review} key={review.id} />)}</div></ProviderShell>;
}

export function ProviderReviewCard({ review }: { review: ProviderReview }) {
  const [responseVisible, setResponseVisible] = useState(Boolean(review.response));
  return <Card className="provider-review-card"><div className="review-card-top"><div><strong>{review.customer_name}</strong><span>{review.date_label}</span></div><Rating value={review.rating} count={0} /></div><span className="eyebrow">{review.service_name}</span><p>{review.comment}</p>{responseVisible ? <div className="provider-response"><strong>Provider response</strong><p>{review.response ?? 'Thanks for sharing your experience. This response is a local preview.'}</p></div> : <Button type="button" variant="quiet" onClick={() => setResponseVisible(true)}>Reply</Button>}</Card>;
}

export function ProviderProfile() {
  return <ProviderShell active="/provider/profile"><ProviderHeading eyebrow="Provider profile" title={providerProfile.business_name} description="Review the public-facing provider profile and verification presentation." action={<Button type="button" variant="secondary" onClick={() => undefined}>Edit profile</Button>} /><div className="provider-profile-grid"><Card className="provider-profile-card"><div className="provider-profile-identity"><div className="provider-avatar provider-avatar-large" aria-hidden="true">BS</div><div><h2>{providerProfile.display_name}</h2><p>{providerProfile.provider_type === 'business' ? 'Business provider' : 'Professional provider'}</p></div></div><Badge tone="success">{providerProfile.verification}</Badge><p>{providerProfile.description}</p><div className="provider-profile-progress"><div><span>Profile completeness</span><strong>{providerProfile.profile_completion}%</strong></div><i><b style={{ width: `${providerProfile.profile_completion}%` }} /></i></div></Card><Card className="provider-profile-card"><span className="eyebrow">Contact and coverage</span><h2>Public details</h2><dl className="provider-profile-details"><div><dt>Email</dt><dd>{providerProfile.email}</dd></div><div><dt>Phone</dt><dd>{providerProfile.phone}</dd></div><div><dt>Service area</dt><dd>{providerProfile.service_area}</dd></div><div><dt>Working hours</dt><dd>{providerProfile.working_hours}</dd></div></dl></Card></div><Card className="provider-profile-card"><div className="section-heading"><div><span className="eyebrow">Catalog summary</span><h2>Services offered</h2></div><Badge tone="info">{providerServices.length} active</Badge></div><div className="provider-profile-services">{providerServices.map((service) => <div key={service.id}><strong>{service.service_name.values.en}</strong><span>{formatMoney(service.pricing.base_price)} · {service.duration_minutes} minutes</span></div>)}</div><p className="provider-fixture-note">Verification and profile details are fixture states. Document upload and review are deferred.</p></Card></ProviderShell>;
}

export function ProviderDashboard() {
  const upcoming = providerBookings.filter((booking) => booking.status === 'scheduled' || booking.status === 'provider_review').slice(0, 2);
  return <ProviderShell active="/provider"><ProviderHeading eyebrow="Provider workspace" title={`Good morning, ${providerProfile.business_name}`} description="A focused overview of today’s schedule, booking activity, services, and customer voice." action={<><Link href="/provider/bookings" className="button button-secondary">Review bookings</Link><Link href="/provider/services" className="button button-primary">Manage services</Link></>} /><div className="provider-summary-grid"><ProviderDashboardSummary label="Today's bookings" value="2" detail="1 upcoming today" tone="info" /><ProviderDashboardSummary label="Pending requests" value="1" detail="Needs a response" tone="warning" /><ProviderDashboardSummary label="Active services" value={`${providerServices.length}`} detail="Catalog is visible" tone="success" /><ProviderDashboardSummary label="Average rating" value="4.8 / 5" detail="334 customer reviews" /></div><div className="provider-dashboard-grid"><Card><div className="section-heading"><div><span className="eyebrow">Today</span><h2>Schedule</h2></div><Link href="/provider/schedule" className="text-link">View schedule</Link></div><div className="provider-schedule-preview"><div><strong>10:00 AM</strong><span>Home electrical inspection</span><small>Ananya Srinivasan · Chennai</small></div><Badge tone="success">Confirmed</Badge><div><strong>2:00 PM</strong><span>Deep home cleaning</span><small>Priya Nair · Chennai</small></div><Badge tone="info">In progress</Badge></div></Card><Card><div className="section-heading"><div><span className="eyebrow">Next actions</span><h2>Booking requests</h2></div><Link href="/provider/bookings" className="text-link">View all</Link></div>{providerBookings.filter((booking) => booking.status === 'provider_review').map((booking) => <div className="provider-request-preview" key={booking.id}><div><strong>{booking.customer_name}</strong><span>{booking.date_label} · {booking.time}</span></div><ProviderStatusBadge status={booking.status} /></div>)}</Card><Card><div className="section-heading"><div><span className="eyebrow">Customer voice</span><h2>Recent reviews</h2></div><Link href="/provider/reviews" className="text-link">View reviews</Link></div>{providerReviews.slice(0, 2).map((review) => <ProviderReviewCard review={review} key={review.id} />)}</Card><Card><div className="section-heading"><div><span className="eyebrow">Performance</span><h2>Earnings snapshot</h2></div><Link href="/provider/earnings" className="text-link">Open earnings</Link></div><div className="provider-earnings-snapshot"><strong>INR 14,680.00</strong><span>This month · fixture data</span></div><div className="provider-quick-actions"><Link href="/provider/profile" className="button button-secondary">Profile status</Link><Link href="/provider/schedule" className="button button-secondary">Set availability</Link></div></Card></div></ProviderShell>;
}
