import { AdminLiveEmptyState, AdminLiveHeading, AdminLiveMetricCard, AdminLiveShell, AdminLiveText } from '../../../components/admin/AdminLiveChrome';
import { Card } from '../../../components/ui/primitives';
import { createSupabaseServerClient } from '../../../lib/supabase/server';
import { productionAuthProvider } from '../../../server/auth/session';

export const dynamic = 'force-dynamic';

type LiveBooking = { id: string; customer_id: string; service_id: string; status: string; quoted_price: number | string; currency: string; created_at: string; };
type LiveService = { id: string; category: string | null; provider_type: string; professional_id: string | null; business_id: string | null; active: boolean; };
type ScopedServiceMapping = { service_id: string; category_id: string | null; };
type PlatformCategory = { id: string; name: string; code: string; };
function formatInr(value: number) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value); }
function monthKey(date: Date) { return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, '0')}`; }
function monthLabel(date: Date) { return new Intl.DateTimeFormat('en-IN', { month: 'short', year: '2-digit', timeZone: 'UTC' }).format(date); }

export default async function AdminReportsRoute() {
  await productionAuthProvider.requireAdmin(); const supabase = await createSupabaseServerClient();
  const { data: mappedScopeData, error: scopeError } = await supabase.from('service_ecosystem_scope').select('service_id,category_id').eq('enabled', true); if (scopeError) throw new Error(scopeError.message);
  const mappedScopes = (mappedScopeData ?? []) as ScopedServiceMapping[]; const serviceIds = Array.from(new Set(mappedScopes.map((row) => String(row.service_id)))); const categoryIds = Array.from(new Set(mappedScopes.map((row) => row.category_id).filter(Boolean))) as string[];
  let bookings: LiveBooking[] = []; let services: LiveService[] = []; let platformCategories: PlatformCategory[] = [];
  if (serviceIds.length) { const [{ data: bookingData, error: bookingError }, { data: serviceData, error: serviceError }] = await Promise.all([supabase.from('bookings').select('id,customer_id,service_id,status,quoted_price,currency,created_at').in('service_id', serviceIds).order('created_at', { ascending: false }).limit(1000), supabase.from('services').select('id,category,provider_type,professional_id,business_id,active').in('id', serviceIds)]); if (bookingError) throw new Error(bookingError.message); if (serviceError) throw new Error(serviceError.message); bookings = (bookingData ?? []) as LiveBooking[]; services = (serviceData ?? []) as LiveService[]; }
  if (categoryIds.length) { const { data: categoryData, error: categoryError } = await supabase.from('platform_categories').select('id,name,code').in('id', categoryIds); if (categoryError) throw new Error(categoryError.message); platformCategories = (categoryData ?? []) as PlatformCategory[]; }

  const totalBookings = bookings.length; const completed = bookings.filter((booking) => booking.status === 'completed').length; const cancelled = bookings.filter((booking) => booking.status === 'cancelled').length; const completionRate = totalBookings ? Math.round((completed / totalBookings) * 100) : 0; const cancellationRate = totalBookings ? Math.round((cancelled / totalBookings) * 100) : 0; const customers = new Set(bookings.map((booking) => booking.customer_id)).size; const activeServices = services.filter((service) => service.active); const providers = new Set(activeServices.map((service) => service.provider_type === 'business' ? service.business_id : service.professional_id).filter(Boolean)).size; const grossActivity = bookings.filter((booking) => booking.status !== 'cancelled').reduce((sum, booking) => sum + Number(booking.quoted_price || 0), 0);
  const now = new Date(); const months = Array.from({ length: 4 }, (_, index) => { const date = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - (3 - index), 1)); return { key: monthKey(date), label: monthLabel(date), count: 0 }; }); const monthMap = new Map(months.map((month) => [month.key, month])); bookings.forEach((booking) => { const entry = monthMap.get(monthKey(new Date(booking.created_at))); if (entry) entry.count += 1; }); const maxMonthCount = Math.max(1, ...months.map((month) => month.count));
  const serviceById = new Map(services.map((service) => [service.id, service])); const categoryById = new Map(platformCategories.map((category) => [category.id, category.name])); const categoryByServiceId = new Map(mappedScopes.map((scope) => [scope.service_id, scope.category_id ? categoryById.get(scope.category_id) ?? null : null])); const categoryCounts = new Map<string, number>();
  bookings.forEach((booking) => { const category = categoryByServiceId.get(booking.service_id) || serviceById.get(booking.service_id)?.category || 'Uncategorised'; categoryCounts.set(category, (categoryCounts.get(category) ?? 0) + 1); }); if (!bookings.length) services.forEach((service) => { const category = categoryByServiceId.get(service.id) || service.category || 'Uncategorised'; categoryCounts.set(category, (categoryCounts.get(category) ?? 0) + 1); });
  const categories = [...categoryCounts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5); const maxCategoryCount = Math.max(1, ...categories.map(([, count]) => count));

  return <AdminLiveShell active="/admin/reports">
    <AdminLiveHeading eyebrow={<AdminLiveText en="Scoped marketplace insights" ta="Scope செய்யப்பட்ட marketplace insights" />} title={<AdminLiveText en="Live reports" ta="நேரடி reports" />} description={<AdminLiveText en="Operational metrics are calculated from live Supabase data and restricted to this administrator’s assigned service scope." ta="Operational metrics live Supabase data-லிருந்து கணக்கிடப்பட்டு, இந்த admin-ன் assigned service scope-க்கு மட்டும் கட்டுப்படுத்தப்படுகின்றன." />} />
    <div className="admin-metric-grid"><AdminLiveMetricCard label={<AdminLiveText en="Booking volume" ta="Booking volume" />} value={`${totalBookings}`} detail={<AdminLiveText en="Live scoped bookings" ta="Live scoped bookings" />} tone="info" /><AdminLiveMetricCard label={<AdminLiveText en="Completion rate" ta="முடிவு விகிதம்" />} value={`${completionRate}%`} detail={<><strong>{completed}</strong> <AdminLiveText en="completed" ta="முடிந்தது" /></>} tone="success" /><AdminLiveMetricCard label={<AdminLiveText en="Cancellation rate" ta="ரத்து விகிதம்" />} value={`${cancellationRate}%`} detail={<><strong>{cancelled}</strong> <AdminLiveText en="cancelled" ta="ரத்து" /></>} tone="warning" /><AdminLiveMetricCard label={<AdminLiveText en="Gross activity" ta="மொத்த activity" />} value={formatInr(grossActivity)} detail={<AdminLiveText en="Non-cancelled scoped value" ta="ரத்து செய்யாத scoped value" />} /><AdminLiveMetricCard label={<AdminLiveText en="Customers" ta="வாடிக்கையாளர்கள்" />} value={`${customers}`} detail={<AdminLiveText en="Distinct scoped customers" ta="தனித்த scoped customers" />} /><AdminLiveMetricCard label={<AdminLiveText en="Active providers" ta="செயலில் உள்ள providers" />} value={`${providers}`} detail={<AdminLiveText en="Providers in scoped services" ta="Scoped services-ல் providers" />} tone="success" /><AdminLiveMetricCard label={<AdminLiveText en="Listed services" ta="பட்டியலிடப்பட்ட சேவைகள்" />} value={`${activeServices.length}`} detail={<AdminLiveText en="Active scoped catalog" ta="Active scoped catalog" />} tone="info" /></div>
    {serviceIds.length ? <div className="admin-report-grid"><Card className="admin-report-card"><span className="eyebrow"><AdminLiveText en="Booking volume" ta="Booking volume" /></span><h2><AdminLiveText en="Recent four months" ta="சமீபத்திய நான்கு மாதங்கள்" /></h2>{months.map((month) => { const width = `${Math.round((month.count / maxMonthCount) * 100)}%`; return <div className="admin-bar-row" key={month.key}><span>{month.label}</span><i><b style={{ width }} /></i><strong>{month.count}</strong></div>; })}</Card><Card className="admin-report-card"><span className="eyebrow"><AdminLiveText en="Scope activity" ta="Scope activity" /></span><h2>{bookings.length ? <AdminLiveText en="Bookings by category" ta="வகை வாரியான bookings" /> : <AdminLiveText en="Services by category" ta="வகை வாரியான services" />}</h2>{categories.length ? categories.map(([label, count]) => { const width = `${Math.round((count / maxCategoryCount) * 100)}%`; return <div className="admin-bar-row" key={label}><span>{label.replaceAll('_', ' ')}</span><i><b style={{ width }} /></i><strong>{count}</strong></div>; }) : <AdminLiveEmptyState titleEn="No category activity yet" titleTa="Category activity இன்னும் இல்லை"><AdminLiveText en="Category reporting will populate with scoped services and bookings." ta="Scoped services மற்றும் bookings வந்ததும் category reporting populate ஆகும்." /></AdminLiveEmptyState>}</Card><Card className="admin-report-card"><span className="eyebrow"><AdminLiveText en="Marketplace health" ta="Marketplace health" /></span><h2><AdminLiveText en="Live scoped summary" ta="Live scoped summary" /></h2><div className="admin-health-list"><p><strong>{providers}</strong><span><AdminLiveText en="Active providers" ta="செயலில் உள்ள providers" /></span></p><p><strong>{customers}</strong><span><AdminLiveText en="Customers" ta="வாடிக்கையாளர்கள்" /></span></p><p><strong>{activeServices.length}</strong><span><AdminLiveText en="Listed services" ta="பட்டியலிடப்பட்ட சேவைகள்" /></span></p></div></Card></div> : <Card><AdminLiveEmptyState titleEn="No assigned scope yet" titleTa="Assigned scope இன்னும் இல்லை"><AdminLiveText en="Reports will populate after services are assigned to this administrator scope." ta="இந்த admin scope-க்கு services assign செய்த பிறகு reports populate ஆகும்." /></AdminLiveEmptyState></Card>}
  </AdminLiveShell>;
}
